### ISSUE TITLE
VolumeRuler always renders in-game with standart size 

### ISSUE THREAD

**Issue by itsgundie** [TrickyFatCat/TrickyLevelHelpers#1]
If VolumeRuler's property "Show in game" is set to true it always renders with standard size 100x100x100.
Used binary engine Version: 5.1.1-23901901+++UE5+Release-5.1.
Plugin from commit 076e332bc402e67e92dea992f34150c0187b546c.
<img width="819" alt="vol_rul_2" src="https://user-images.githubusercontent.com/49826242/235373982-f3a7f277-e1b8-4d73-b502-6c2bded572f4.png">
<img width="853" alt="vol_rul_1" src="https://user-images.githubusercontent.com/49826242/235373987-86347c43-e15f-4a78-8d01-14e02853c592.png">

**Comment by TrickyFatCat** [comment]
Thank you for the information, will check it.

**Comment by TrickyFatCat** [comment]
Fix is in version 2.1.1
